name: Github Actions Test

on: 
  push:
    branches: 
      - "main"
      - "master"

  pull_request:
    types:
      - opened
    branches:
      - main

  workflow_call:
    inputs:
      username0:
        type: string
        default: "Umit"


  workflow_dispatch:
      inputs:
        username1:
          type: string
          default: "Umit"

env:
  name0: Umit0
  
  
jobs:
  job1:
    name: Job1
    runs-on: ubuntu-latest
    env:
      name1: Umit1

    steps:
      - name: Step1
        run: "uname -a"
      - name: Step2
        run: "uptime"
      - name: Step3
        run: |
          echo "name1: ${{ env.name1}}"
          echo $name1
          echo $name0

  job2:
    name: Job2
    runs-on: ubuntu-latest
    needs: job1
    outputs:
      last_name1: seremet1
      last_name2: ${{ steps.Step3.outputs.last_name2 }}
    env:
      name2: Umit2

    steps:
      - name: Step1
        run: "uname -a"
      - name: Step2
        run: "uptime"
      - name: Step3
        run: |
          echo "name2: ${{ env.name2 }}"
          echo "name0: $name0"
          echo "USERNAME0: ${{ inputs.username0 }}"
          echo "USERNAME1: ${{ inputs.username1 }}" 
          echo "last_name2=seremet2" >> $GITHUB_OUTPUT    

