name: Reusable Workflow

on:
  workflow_call:
    inputs:
        var1:
            description: name
            required: true
            default: "Umit"
            type: string
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo job1step1
      - name: UptimeVeersionDetect
        run: |
          uptime
          uname -a
      - name: PrintName
        shell: bash
        run: |
            echo "Name: ${{ inputs.var1 }}"

  job2:
    name: job2
    runs-on: ubuntu-latest
    steps:
     - name: step1
       run: echo job2step1
     - name: step2
       run: echo job2step2       
     - name: step3
       run: echo job2step3